import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'

import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode? "dark":""} >
      <Head>
        <title>Practice Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl dark:text-white '>Abhishek</h1>
              <ul className='flex items-center'>
                <li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-white'>Abhishek Saini</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer.</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Freelancer providing services for programming and design content needs. Join me down below and let's get cracking</p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillTwitterCircle/>
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved}  layout='fill' objectFit='cover'/>
            </div>
        </section>

        <section  >
          <h3 className='text-3xl py-1 dark:text-white'>Services I Offer</h3>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            Since the beginning of my journey as a freelancer designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span> consulted for <span className='text-teal-500'>startups </span>and collabrated with talented people to create digital products for both business and consumer use.
          </p>
          <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>
            I offer from a wide range of services, including brand design, programming and teaching.
          </p>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'  >
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Programming</h3>
              <p className='py-2 '>Write best and code for software suited for your needs following core coding theory.</p>
              <h4 className='py-4 text-teal-600'>Programming tools I use</h4>
              <p className='text-gray-800 py-1'>VS Code</p>
              <p className='text-gray-800 py-1'>Atom</p>
              <p className='text-gray-800 py-1'>IDE's</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'  >
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Consulting</h3>
              <p className='py-2'>Provide consulting for design and programming suited for your needs following core consulting theory.</p>
              <h4 className='py-4 text-teal-600'>Software I use</h4>
              <p className='text-gray-800 py-1'>Google Meet</p>
              <p className='text-gray-800 py-1'>Zoom</p>
              <p className='text-gray-800 py-1'>Microsoft Teams</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'  >
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Creating elegant design suited for your needs following core design theory.</p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Canva</p>
              <p className='text-gray-800 py-1'>Photoshop</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae facere eius nostrum nemo illo natus <span className='text-teal-500'>hello</span> esse in nesciunt dicta veritatis quasi accusamus, itaque tenetur nam <span className='text-teal-500'>placeat</span>, placeat ullam fugiat doloribus odio asperiores eaque. Dicta illum cum eos ea animi.</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>I offer from a wide range of services, including brand design, programming and teaching.</p>
          </div>

          <div className='flex flex-col gap-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web2} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web1} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web3} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web4} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web5} /></div>
            <div className='basis-1/3 flex-1'><Image className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' src={web6} /></div>
          </div>
        </section>
      </main>

 
    </div>
  )
}
